services:
  - type: web
    name: glowflix-proxy
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production